# -*- coding: utf-8 -*-
"""Thompson Sampling Algorithm Facebook Ads.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12QwKAAtn9R-34M1L8l8j7ypwKQSIp9mc

Importing Libraries
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""Importing Darasetr"""

dataset = pd.read_csv('/content/Facebook Ads.csv')

"""Implementation"""

import random
N = 200
num_ads = 10
ads_selected = []
num_of_rewards_1 = [0] * num_ads
num_of_rewards_0 = [0] * num_ads
total_reward = 0
for n in range(0, N):
  ad = 0
  max_random = 0
  for i in range(0, num_ads):
    random_beta = random.betavariate(num_of_rewards_1[i] + 1, num_of_rewards_0[i] + 1)
    if (random_beta > max_random):
      max_random = random_beta
      ad = i
  ads_selected.append(ad)
  reward = dataset.values[n, ad]
  if reward == 1:
    num_of_rewards_1[ad] = num_of_rewards_1[ad] + 1
  else:
    num_of_rewards_0[ad] = num_of_rewards_0[ad] + 1
  total_reward = total_reward + reward

"""Histogram Visualization"""

plt.hist(ads_selected)
plt.title('Histogram of ads selections')
plt.xlabel('Ads')
plt.ylabel('Number of times each ad was selected')
plt.show()

